#!/bin/bash
## Reference:
## [1] https://github.com/sameersbn/docker-gitlab

set -e

export JDK_URL=http://archive.cloudera.com/director/redhat/7/x86_64/director/2.5/RPMS/x86_64/oracle-j2sdk1.8-1.8.0+update121-1.x86_64.rpm

/app/setup/jdk/install
/app/setup/cloudera-director/install
