#!/bin/bash
## Reference:
## [1] https://github.com/sameersbn/docker-gitlab

set -e

export JDK_URL=http://archive.cloudera.com/director/redhat/7/x86_64/director/2.3.0/RPMS/x86_64/jdk-8u60-linux-x64.rpm

/app/setup/jdk/install
/app/setup/cloudera-director/install
